;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; 4 Op-blocks world
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain MYBLOCKS)
  (:requirements :strips :equality)

  (:predicates
    (on ?x ?y)
    (ontable ?x)
    (clear ?x)
    (handempty)
    (holding ?x)
    (backflip ?x)
  )

  (:action pick-up
    :parameters (?x ?y ?z ?a ?b ?c ?d)
    :precondition (and
      (clear ?x)
      (ontable ?x)
      (handempty)

      (not (= ?x ?y))
      (not (= ?x ?z))
      (not (= ?x ?a))
      (not (= ?x ?b))
      (not (= ?x ?c))
      (not (= ?x ?d))
      (not (= ?y ?z))
      (not (= ?y ?a))
      (not (= ?y ?b))
      (not (= ?y ?c))
      (not (= ?y ?d))
      (not (= ?z ?a))
      (not (= ?z ?b))
      (not (= ?z ?c))
      (not (= ?z ?d))
      (not (= ?a ?b))
      (not (= ?a ?c))
      (not (= ?a ?d))
      (not (= ?b ?c))
      (not (= ?b ?d))
      (not (= ?c ?d))
    )
    :effect (and
      (not (ontable ?x))
      (not (clear ?x))
      (not (handempty))
      (holding ?x)
      (backflip ?x)
      (not (backflip ?y))
      (not (backflip ?z))
      (not (backflip ?a))
      (not (backflip ?b))
      (not (backflip ?c))
      (not (backflip ?d))
    )
  )

  (:action put-down
    :parameters (?x ?y ?z ?a ?b ?c ?d)
    :precondition (and
      (holding ?x)

      (not (= ?x ?y))
      (not (= ?x ?z))
      (not (= ?x ?a))
      (not (= ?x ?b))
      (not (= ?x ?c))
      (not (= ?x ?d))
      (not (= ?y ?z))
      (not (= ?y ?a))
      (not (= ?y ?b))
      (not (= ?y ?c))
      (not (= ?y ?d))
      (not (= ?z ?a))
      (not (= ?z ?b))
      (not (= ?z ?c))
      (not (= ?z ?d))
      (not (= ?a ?b))
      (not (= ?a ?c))
      (not (= ?a ?d))
      (not (= ?b ?c))
      (not (= ?b ?d))
      (not (= ?c ?d))
    )
    :effect (and
      (not (holding ?x))
      (clear ?x)
      (handempty)
      (ontable ?x)
      (not (backflip ?x))
      (backflip ?y)
      (backflip ?z)
      (backflip ?a)
      (backflip ?b)
      (backflip ?c)
      (backflip ?d)
    )
  )

  (:action stack
    :parameters (?x ?y ?z ?a ?b ?c ?d)
    :precondition (and
      (holding ?x)
      (clear ?y)

      (not (= ?x ?y))
      (not (= ?x ?z))
      (not (= ?x ?a))
      (not (= ?x ?b))
      (not (= ?x ?c))
      (not (= ?x ?d))
      (not (= ?y ?z))
      (not (= ?y ?a))
      (not (= ?y ?b))
      (not (= ?y ?c))
      (not (= ?y ?d))
      (not (= ?z ?a))
      (not (= ?z ?b))
      (not (= ?z ?c))
      (not (= ?z ?d))
      (not (= ?a ?b))
      (not (= ?a ?c))
      (not (= ?a ?d))
      (not (= ?b ?c))
      (not (= ?b ?d))
      (not (= ?c ?d))
    )
    :effect (and
      (not (holding ?x))
      (not (clear ?y))
      (clear ?x)
      (handempty)
      (on ?x ?y)
      (not (backflip ?x))
      (backflip ?y)
      (backflip ?z)
      (backflip ?a)
      (backflip ?b)
      (backflip ?c)
      (backflip ?d)
    )
  )

  (:action unstack
    :parameters (?x ?y ?z ?a ?b ?c ?d)
    :precondition (and
      (on ?x ?y)
      (clear ?x)
      (handempty)

      (not (= ?x ?y))
      (not (= ?x ?z))
      (not (= ?x ?a))
      (not (= ?x ?b))
      (not (= ?x ?c))
      (not (= ?x ?d))
      (not (= ?y ?z))
      (not (= ?y ?a))
      (not (= ?y ?b))
      (not (= ?y ?c))
      (not (= ?y ?d))
      (not (= ?z ?a))
      (not (= ?z ?b))
      (not (= ?z ?c))
      (not (= ?z ?d))
      (not (= ?a ?b))
      (not (= ?a ?c))
      (not (= ?a ?d))
      (not (= ?b ?c))
      (not (= ?b ?d))
      (not (= ?c ?d))
    )
    :effect (and
      (holding ?x)
      (clear ?y)
      (not (clear ?x))
      (not (handempty))
      (not (on ?x ?y))
      (backflip ?x)
      (not (backflip ?y))
      (not (backflip ?z))
      (not (backflip ?a))
      (not (backflip ?b))
      (not (backflip ?c))
      (not (backflip ?d))
    )
  )
)